WarehouseMVC.Web/Models/ErrorViewModel.cs
using System;

namespace WarehouseMVC.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WarehouseMVC.Web/Models/Item.cs
using System;
using System.ComponentModel;

namespace WarehouseMVC.Web.Models
{
    public class Item
    {
        [DisplayName("Identyfikator")]
        public int Id { get; set; }
        [DisplayName("Imie")]
        public string Name { get; set; }
        public string ItemType { get; set; }
    }
}

WarehouseMVC.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WarehouseMVC.Application.Interfaces;
using WarehouseMVC.Application.ViewModels.Customer;

namespace WarehouseMVC.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _customerService.GetAllCustomerForList(1, 1, "");

            return View(model);
        }

        //pageSize - jak dużo rekordów na stronie
        //pageNumber - którą stronę wyświetlić
        //searchString - wyszukiwanie po nazwie
        [HttpPost]
        public IActionResult Index(int pageSize, int? pageNumber, string searchString)
        {
            if (!pageNumber.HasValue)
            {
                pageNumber = 1;
            }

            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _customerService.GetAllCustomerForList(pageSize, pageNumber.Value, searchString);

            return View(model);
        }

        [HttpGet]
        public IActionResult ViewCustomer(int id)
        {
            var model = _customerService.GetCustomerDetails(id);

            return View(model);
        }

        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View(new NewCustomerVm());
        }

        [HttpPost]
        public IActionResult AddCustomer(NewCustomerVm model)
        {
            var id = _customerService.AddCustomer(model);
            return RedirectToAction("Index");
        }


        //[HttpPost]
        //public IActionResult AddCustomer(CustomerModel model)
        //{
        //    var id = customerService.AddCustomer(model);
        //    return View();
        //}

        [HttpGet]
        public IActionResult AddNewAddressForClient(int customerId)
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult AddNewAddressForClient(ClientModel model)
        //{
        //    return View();
        //}


    }
}

WarehouseMVC.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WarehouseMVC.Web.Models;

namespace WarehouseMVC.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        //ViewListOfItems?id=1&name=nazwa
        public IActionResult ViewListOfItems(int id, string name)
        {
            List<Item> items = new List<Item>();
            items.Add(new Item() { Id = 1, Name = "Apple", ItemType = "Grocery" });
            items.Add(new Item() { Id = 2, Name = "Strawberry", ItemType = "Grocery" });
            items.Add(new Item() { Id = 3, Name = "Banana", ItemType = "Grocery" });

            return View(items);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WarehouseMVC.Web/Views/Customer/AddCustomer.cshtml
@model WarehouseMVC.Application.ViewModels.Customer.NewCustomerVm

@{
    ViewData["Title"] = "AddCustomer";
}

<h1>AddCustomer</h1>

<h4>NewCustomerVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCustomer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id"></input>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NIP" class="control-label"></label>
                <input asp-for="NIP" class="form-control" />
                <span asp-validation-for="NIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="REGON" class="control-label"></label>
                <input asp-for="REGON" class="form-control" />
                <span asp-validation-for="REGON" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WarehouseMVC.Web/Views/Customer/Index.cshtml
@model WarehouseMVC.Application.ViewModels.Customer.ListCustomerForListVm

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="AddCustomer">Create New</a>
</p>
<form asp-action="Index" asp-controller="Customer" method="post">
    <div class="row">
        <input type="text" asp-for="SearchString" name="searchString" id="searchString" />
        <input type="submit" value="Search" />
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        NIP
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Customers)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NIP)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "ViewCustomer", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <table>
            <tr>
                @for (int i = 1; i <= Math.Ceiling(Model.Count / (double)Model.PageSize); i++)
                {
                    <td>
                        @if (i != Model.CurrentPage)
                        {
                            <a href="javascript:PagerClick(@i)">@i</a>
                        }
                        else
                        {
                            <span>@i</span>
                        }
                    </td>
                }
            </tr>
        </table>
        <input type="hidden" name="pageNumber" id="pageNumber" />
        <input type="hidden" name="pageSize" id="pageSize" value="1" />
    </div>
</form>

@section Scripts
{
    <script type="text/javascript">
        function PagerClick(index)
        {
            document.getElementById("pageNumber").value = index;
            document.forms[0].submit();
        }
    </script>
}

WarehouseMVC.Web/Views/Customer/ViewCustomer.cshtml
@model WarehouseMVC.Application.ViewModels.Customer.CustomerDetailsVm

@{
    ViewData["Title"] = "ViewCustomer";
}

<h1>ViewCustomer</h1>

<div>
    <h4>CustomerDetailsVm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.REGON)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.REGON)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CEOFullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CEOFullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstLineOfContactInformation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstLineOfContactInformation)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WarehouseMVC.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WarehouseMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WarehouseMVC.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WarehouseMVC.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WarehouseMVC.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>